Made predictions for solar flare, added linting
janaSunrise/sklearn-datasets-implementation pull request #6
Opened 2020-12-12 09:08 UTC by Rohith04MVK

2020-12-12 09:30 UTC, Rohith04MVK commented
I have linted everything

2020-12-12 10:55 UTC, janaSunrise requested changes
Do the changes to be approved 👍🏼

2020-12-12 10:55 UTC, janaSunrise commented on src/solar-flare/main.py
> +
```suggestion

```

Change it to one line :)

2020-12-12 10:55 UTC, janaSunrise commented on src/solar-flare/main.py
> +
```suggestion

```

Same here ;)

2020-12-16 17:57 UTC, janaSunrise approved these changes
Great! 👍🏼

2020-12-16 17:57 UTC, merged